// Mock data for demo mode (when Supabase is not connected)
import type { Doctor, Specialty } from "./types";

export const MOCK_SPECIALTIES: Specialty[] = [
  { id: "plastik_cerrahi", name_tr: "Plastik ve Estetik Cerrahi", name_en: "Plastic & Aesthetic Surgery", slug: "plastic-surgery", description_tr: null, description_en: null, icon: null },
  { id: "goz_hastaliklari", name_tr: "Goz Hastaliklari", name_en: "Ophthalmology", slug: "ophthalmology", description_tr: null, description_en: null, icon: null },
  { id: "dis_hekimligi", name_tr: "Dis Hekimligi", name_en: "Dentistry", slug: "dentistry", description_tr: null, description_en: null, icon: null },
  { id: "ortopedi", name_tr: "Ortopedi ve Travmatoloji", name_en: "Orthopedics & Traumatology", slug: "orthopedics", description_tr: null, description_en: null, icon: null },
  { id: "genel_cerrahi", name_tr: "Genel Cerrahi", name_en: "General Surgery", slug: "general-surgery", description_tr: null, description_en: null, icon: null },
  { id: "kardiyoloji", name_tr: "Kardiyoloji", name_en: "Cardiology", slug: "cardiology", description_tr: null, description_en: null, icon: null },
  { id: "dermatoloji", name_tr: "Dermatoloji", name_en: "Dermatology", slug: "dermatology", description_tr: null, description_en: null, icon: null },
  { id: "sac_ekimi", name_tr: "Sac Ekimi", name_en: "Hair Transplant", slug: "hair-transplant", description_tr: null, description_en: null, icon: null },
];

const now = new Date().toISOString();

export const MOCK_DOCTORS: Doctor[] = [
  { id: "1", title: "Op. Dr.", first_name: "Meltem", last_name: "Tokel", slug: "op-dr-meltem-tokel", specialty_id: "plastik_cerrahi", city: "Istanbul", address: "Caddebostan Mah. Mehtap Sok. No:40/1 Kadikoy", phone: "0 507 208 75 95", lat: 40.97, lng: 29.06, bio_tr: "Op. Dr. Meltem Tokel, Istanbul'da plastik ve estetik cerrahi alaninda uzmanlasmis deneyimli bir cerrahtir.", bio_en: "Op. Dr. Meltem Tokel is an experienced plastic and aesthetic surgeon practicing in Istanbul, Turkey.", meta_tr: "Op. Dr. Meltem Tokel - Istanbul Plastik Cerrahi", meta_en: "Op. Dr. Meltem Tokel - Plastic Surgery Istanbul", photo_url: null, verified: true, claimed: false, source_table: "muayenehaneler", original_name: "Op. Dr. Meltem Tokel Kayis Muayenehanesi", rating_avg: 4.8, review_count: 24, created_at: now, updated_at: now, specialty: MOCK_SPECIALTIES[0] },
  { id: "2", title: "Doc. Dr.", first_name: "Baris", last_name: "Boke", slug: "doc-dr-baris-boke", specialty_id: "plastik_cerrahi", city: "Adana", address: "Kurtulus Mah. Ziyapasa Blv.", phone: "0 546 148 78 78", lat: 37.0, lng: 35.32, bio_tr: "Doc. Dr. Baris Boke, Adana'da plastik cerrahi alaninda hizmet vermektedir.", bio_en: "Assoc. Prof. Baris Boke is a plastic surgeon serving patients in Adana, Turkey.", meta_tr: "Doc. Dr. Baris Boke - Adana Plastik Cerrahi", meta_en: "Assoc. Prof. Baris Boke - Plastic Surgery Adana", photo_url: null, verified: true, claimed: false, source_table: "muayenehaneler", original_name: "Doc.Dr. Baris Boke Muayenehanesi", rating_avg: 4.6, review_count: 18, created_at: now, updated_at: now, specialty: MOCK_SPECIALTIES[0] },
  { id: "3", title: "Prof. Dr.", first_name: "Ahmet", last_name: "Yilmaz", slug: "prof-dr-ahmet-yilmaz", specialty_id: "kardiyoloji", city: "Ankara", address: "Kizilay Mah. Ataturk Blv. No:12", phone: "0 312 445 67 89", lat: 39.92, lng: 32.85, bio_tr: "Prof. Dr. Ahmet Yilmaz, Ankara'da kardiyoloji alaninda taninmis bir uzmandir.", bio_en: "Prof. Dr. Ahmet Yilmaz is a renowned cardiologist based in Ankara, Turkey.", meta_tr: "Prof. Dr. Ahmet Yilmaz - Ankara Kardiyoloji", meta_en: "Prof. Dr. Ahmet Yilmaz - Cardiology Ankara", photo_url: null, verified: true, claimed: false, source_table: "muayenehaneler", original_name: "Prof. Dr. Ahmet Yilmaz Muayenehanesi", rating_avg: 4.9, review_count: 42, created_at: now, updated_at: now, specialty: MOCK_SPECIALTIES[5] },
  { id: "4", title: "Op. Dr.", first_name: "Elif", last_name: "Demir", slug: "op-dr-elif-demir", specialty_id: "goz_hastaliklari", city: "Istanbul", address: "Besiktas Mah. Barbaros Blv. No:8", phone: "0 212 555 34 56", lat: 41.04, lng: 29.0, bio_tr: "Op. Dr. Elif Demir, Istanbul'da goz hastaliklari ve cerrahisi alaninda uzmandir.", bio_en: "Op. Dr. Elif Demir specializes in ophthalmology and eye surgery in Istanbul, Turkey.", meta_tr: "Op. Dr. Elif Demir - Istanbul Goz Hastaliklari", meta_en: "Op. Dr. Elif Demir - Ophthalmology Istanbul", photo_url: null, verified: true, claimed: false, source_table: "muayenehaneler", original_name: "Op. Dr. Elif Demir Goz Muayenehanesi", rating_avg: 4.7, review_count: 31, created_at: now, updated_at: now, specialty: MOCK_SPECIALTIES[1] },
  { id: "5", title: "Dr.", first_name: "Mehmet", last_name: "Ozturk", slug: "dr-mehmet-ozturk", specialty_id: "dis_hekimligi", city: "Izmir", address: "Alsancak Mah. Kibris Sehitleri Cad. No:22", phone: "0 232 463 78 90", lat: 38.43, lng: 27.14, bio_tr: "Dr. Mehmet Ozturk, Izmir'de modern dis hekimligi hizmeti sunmaktadir.", bio_en: "Dr. Mehmet Ozturk provides modern dental services in Izmir, Turkey.", meta_tr: "Dr. Mehmet Ozturk - Izmir Dis Hekimligi", meta_en: "Dr. Mehmet Ozturk - Dentistry Izmir", photo_url: null, verified: true, claimed: false, source_table: "diger_saglik", original_name: "Dr. Mehmet Ozturk Dis Klinigi", rating_avg: 4.5, review_count: 15, created_at: now, updated_at: now, specialty: MOCK_SPECIALTIES[2] },
  { id: "6", title: "Op. Dr.", first_name: "Zeynep", last_name: "Kara", slug: "op-dr-zeynep-kara", specialty_id: "genel_cerrahi", city: "Antalya", address: "Muratpasa Mah. Ismet Pasa Cad. No:5", phone: "0 242 334 56 78", lat: 36.89, lng: 30.71, bio_tr: "Op. Dr. Zeynep Kara, Antalya'da genel cerrahi alaninda hizmet vermektedir.", bio_en: "Op. Dr. Zeynep Kara is a general surgeon practicing in Antalya, Turkey.", meta_tr: "Op. Dr. Zeynep Kara - Antalya Genel Cerrahi", meta_en: "Op. Dr. Zeynep Kara - General Surgery Antalya", photo_url: null, verified: true, claimed: false, source_table: "muayenehaneler", original_name: "Op. Dr. Zeynep Kara Muayenehanesi", rating_avg: 4.4, review_count: 9, created_at: now, updated_at: now, specialty: MOCK_SPECIALTIES[4] },
  { id: "7", title: "Uzm. Dr.", first_name: "Can", last_name: "Aksoy", slug: "uzm-dr-can-aksoy", specialty_id: "dermatoloji", city: "Istanbul", address: "Sisli Mah. Halaskargazi Cad. No:44", phone: "0 212 233 45 67", lat: 41.06, lng: 28.99, bio_tr: "Uzm. Dr. Can Aksoy, Istanbul'da dermatoloji ve sac ekimi konularinda uzmandir.", bio_en: "Specialist Dr. Can Aksoy focuses on dermatology and hair transplant procedures in Istanbul.", meta_tr: "Uzm. Dr. Can Aksoy - Istanbul Dermatoloji", meta_en: "Dr. Can Aksoy - Dermatology & Hair Transplant Istanbul", photo_url: null, verified: true, claimed: false, source_table: "muayenehaneler", original_name: "Uzm. Dr. Can Aksoy Dermatoloji", rating_avg: 4.3, review_count: 12, created_at: now, updated_at: now, specialty: MOCK_SPECIALTIES[6] },
  { id: "8", title: "Op. Dr.", first_name: "Ayse", last_name: "Celik", slug: "op-dr-ayse-celik", specialty_id: "ortopedi", city: "Bursa", address: "Osmangazi Mah. Cekirge Cad. No:18", phone: "0 224 567 89 01", lat: 40.19, lng: 29.06, bio_tr: "Op. Dr. Ayse Celik, Bursa'da ortopedi ve travmatoloji uzmanıdır.", bio_en: "Op. Dr. Ayse Celik is an orthopedic surgeon based in Bursa, Turkey.", meta_tr: "Op. Dr. Ayse Celik - Bursa Ortopedi", meta_en: "Op. Dr. Ayse Celik - Orthopedics Bursa", photo_url: null, verified: false, claimed: false, source_table: "muayenehaneler", original_name: "Op. Dr. Ayse Celik Muayenehanesi", rating_avg: 4.2, review_count: 7, created_at: now, updated_at: now, specialty: MOCK_SPECIALTIES[3] },
];
